import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const contentRoot = path.join(projectRoot, "content", "docs");
const outputFile = path.join(projectRoot, "lib", "docs.generated.ts");
const blogContentRoot = path.join(projectRoot, "content", "blog");
const blogOutputFile = path.join(projectRoot, "lib", "blog.generated.ts");
const standardsContentRoot = path.resolve(projectRoot, "..", "docs", "standards");
const standardsOutputFile = path.join(projectRoot, "lib", "standards.generated.ts");

function parseFrontMatter(source, filename) {
  const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error(`${filename}: missing front matter`);
  const metadata = Object.fromEntries(
    match[1].split("\n").filter(Boolean).map((line) => {
      const separator = line.indexOf(":");
      if (separator < 0) throw new Error(`${filename}: invalid front matter line: ${line}`);
      return [line.slice(0, separator).trim(), line.slice(separator + 1).trim()];
    }),
  );
  return { metadata, body: match[2].trim() };
}

function parseDocument(source, locale, filename) {
  const { metadata, body } = parseFrontMatter(source, filename);
  const slug = filename.replace(/\.md$/, "");
  const required = ["title", "description", "section", "order", "status"];
  for (const field of required) if (!metadata[field]) throw new Error(`${filename}: missing ${field}`);
  return {
    locale,
    slug,
    title: metadata.title,
    description: metadata.description,
    section: metadata.section,
    order: Number(metadata.order),
    status: metadata.status,
    body,
  };
}

function parseBlogPost(source, locale, filename) {
  const { metadata, body } = parseFrontMatter(source, filename);
  const slug = filename.replace(/\.md$/, "");
  const required = ["title", "description", "published", "author", "category"];
  for (const field of required) if (!metadata[field]) throw new Error(`${filename}: missing ${field}`);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(metadata.published)) {
    throw new Error(`${filename}: published must use YYYY-MM-DD`);
  }
  return {
    locale,
    slug,
    title: metadata.title,
    description: metadata.description,
    published: metadata.published,
    author: metadata.author,
    category: metadata.category,
    body,
  };
}

function parseStandard(source, locale, filename) {
  const titleMatch = source.match(/^#\s+(.+)$/m);
  if (!titleMatch) throw new Error(`${filename}: missing level-one title`);
  const slug = filename.replace(/\.md$/, "");
  const body = source.replace(/^#\s+.+\n+/, "").trim();
  const sourcePath = locale === "zh"
    ? `docs/standards/zh-CN/${filename}`
    : `docs/standards/${filename}`;
  return { locale, slug, title: titleMatch[1].trim(), sourcePath, body };
}

const documents = [];
for (const locale of ["zh", "en"]) {
  const directory = path.join(contentRoot, locale);
  for (const filename of (await readdir(directory)).filter((name) => name.endsWith(".md")).sort()) {
    documents.push(parseDocument(await readFile(path.join(directory, filename), "utf8"), locale, filename));
  }
}

await mkdir(path.dirname(outputFile), { recursive: true });
await writeFile(outputFile, `// Generated by scripts/generate-docs.mjs. Do not edit.\nexport const generatedDocs = ${JSON.stringify(documents, null, 2)} as const;\n`);

const blogPosts = [];
for (const locale of ["zh", "en"]) {
  const directory = path.join(blogContentRoot, locale);
  for (const filename of (await readdir(directory)).filter((name) => name.endsWith(".md")).sort()) {
    blogPosts.push(parseBlogPost(await readFile(path.join(directory, filename), "utf8"), locale, filename));
  }
}

await writeFile(blogOutputFile, `// Generated by scripts/generate-docs.mjs. Do not edit.\nexport const generatedBlogs = ${JSON.stringify(blogPosts, null, 2)} as const;\n`);

const standardDocuments = [];
for (const [locale, directory] of [["en", standardsContentRoot], ["zh", path.join(standardsContentRoot, "zh-CN")]]) {
  for (const filename of (await readdir(directory)).filter((name) => name.endsWith(".md") && name !== "README.md" && name !== "IPR_STATUS.md").sort()) {
    standardDocuments.push(parseStandard(await readFile(path.join(directory, filename), "utf8"), locale, filename));
  }
}

await writeFile(standardsOutputFile, `// Generated by scripts/generate-docs.mjs. Do not edit.\nexport const generatedStandards = ${JSON.stringify(standardDocuments, null, 2)} as const;\n`);
console.log(`Generated ${documents.length} documentation pages, ${blogPosts.length} blog pages, and ${standardDocuments.length} standards pages.`);
