import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const contentRoot = path.join(projectRoot, "content", "docs");
const outputFile = path.join(projectRoot, "lib", "docs.generated.ts");

function parseDocument(source, locale, filename) {
  const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error(`${filename}: missing front matter`);
  const metadata = Object.fromEntries(
    match[1].split("\n").filter(Boolean).map((line) => {
      const separator = line.indexOf(":");
      if (separator < 0) throw new Error(`${filename}: invalid front matter line: ${line}`);
      return [line.slice(0, separator).trim(), line.slice(separator + 1).trim()];
    }),
  );
  const slug = filename.replace(/\.md$/, "");
  const required = ["title", "description", "section", "order", "status"];
  for (const field of required) if (!metadata[field]) throw new Error(`${filename}: missing ${field}`);
  return {
    locale,
    slug,
    title: metadata.title,
    description: metadata.description,
    section: metadata.section,
    order: Number(metadata.order),
    status: metadata.status,
    body: match[2].trim(),
  };
}

const documents = [];
for (const locale of ["zh", "en"]) {
  const directory = path.join(contentRoot, locale);
  for (const filename of (await readdir(directory)).filter((name) => name.endsWith(".md")).sort()) {
    documents.push(parseDocument(await readFile(path.join(directory, filename), "utf8"), locale, filename));
  }
}

await mkdir(path.dirname(outputFile), { recursive: true });
await writeFile(outputFile, `// Generated by scripts/generate-docs.mjs. Do not edit.\nexport const generatedDocs = ${JSON.stringify(documents, null, 2)} as const;\n`);
console.log(`Generated ${documents.length} documentation pages.`);
