#!/usr/bin/env python3
"""Generate deterministic third-party license bundles for release artifacts."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
LICENSE_PREFIXES = ("license", "licence", "copying", "notice", "copyright")
MAX_LICENSE_BYTES = 1_048_576
FALLBACK_LICENSES = {
    "Apache-2.0": REPOSITORY_ROOT / "LICENSE",
    "MIT": REPOSITORY_ROOT / "third_party" / "licenses" / "MIT.txt",
    "BSD-2-Clause": REPOSITORY_ROOT / "third_party" / "licenses" / "BSD-2-Clause.txt",
    "BSL-1.0": REPOSITORY_ROOT / "third_party" / "licenses" / "BSL-1.0.txt",
}


def license_files(package_directory: Path, explicit: str | None = None) -> list[Path]:
    candidates: set[Path] = set()
    if explicit:
        explicit_path = Path(explicit)
        if not explicit_path.is_absolute():
            explicit_path = package_directory / explicit_path
        candidates.add(explicit_path)
    if package_directory.is_dir():
        for child in package_directory.iterdir():
            if child.is_file() and child.name.lower().startswith(LICENSE_PREFIXES):
                candidates.add(child)
    return sorted(
        (
            candidate
            for candidate in candidates
            if candidate.is_file() and candidate.stat().st_size <= MAX_LICENSE_BYTES
        ),
        key=lambda candidate: candidate.name.lower(),
    )


def read_license(path: Path) -> str:
    text = path.read_text(encoding="utf-8", errors="replace")
    return "\n".join(line.rstrip() for line in text.splitlines()).strip()


def fallback_license_files(expression: str) -> list[Path]:
    """Resolve an SPDX OR-expression to one distributable permissive license."""
    for identifier in ("Apache-2.0", "MIT", "BSD-2-Clause", "BSL-1.0"):
        if identifier in expression:
            return [FALLBACK_LICENSES[identifier]]
    return []


def git_workspace_license_files(package_directory: Path) -> list[Path]:
    """Find licenses inherited from the root of a Cargo git workspace."""
    for ancestor in package_directory.parents:
        if (ancestor / ".git").exists():
            return license_files(ancestor)
    return []


def render_bundle(
    title: str,
    provenance: str,
    packages: list[tuple[str, str, str, list[Path]]],
) -> str:
    texts: dict[str, str] = {}
    packages_by_text: dict[str, set[str]] = defaultdict(set)
    inventory: list[tuple[str, str, list[str]]] = []
    missing: list[str] = []

    for name, version, license_expression, paths in sorted(packages):
        references: list[str] = []
        for path in paths:
            text = read_license(path)
            if not text:
                continue
            digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
            texts[digest] = text
            packages_by_text[digest].add(f"{name} {version}")
            references.append(digest)
        if not references:
            missing.append(f"{name} {version} ({license_expression})")
        inventory.append((f"{name} {version}", license_expression, sorted(set(references))))

    if missing:
        joined = "\n  - ".join(missing)
        raise RuntimeError(f"packages without bundled license text:\n  - {joined}")

    ordered_digests = sorted(texts)
    labels = {digest: f"L{index:03d}" for index, digest in enumerate(ordered_digests, 1)}
    lines = [
        f"# {title}",
        "",
        "> Generated by `scripts/generate-third-party-licenses.py`; do not edit manually.",
        "> Regenerate whenever the corresponding lockfile changes.",
        "",
        provenance,
        "",
        "## Package inventory",
        "",
        "| Package | Declared license | Included texts |",
        "|---|---|---|",
    ]
    for package, expression, references in inventory:
        reference_list = ", ".join(labels[reference] for reference in references)
        lines.append(f"| `{package}` | `{expression}` | {reference_list} |")

    lines.extend(["", "## License texts", ""])
    for digest in ordered_digests:
        label = labels[digest]
        covered = ", ".join(f"`{package}`" for package in sorted(packages_by_text[digest]))
        lines.extend(
            [
                f"### {label}",
                "",
                f"Applies to: {covered}",
                "",
                "~~~~text",
                texts[digest],
                "~~~~",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def rust_packages() -> list[tuple[str, str, str, list[Path]]]:
    result = subprocess.run(
        ["cargo", "metadata", "--locked", "--format-version", "1"],
        cwd=REPOSITORY_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    metadata = json.loads(result.stdout)
    packages_by_id = {package["id"]: package for package in metadata["packages"]}
    nodes_by_id = {node["id"]: node for node in metadata["resolve"]["nodes"]}
    workspace_ids = set(metadata["workspace_members"])
    roots = [
        package["id"]
        for package in metadata["packages"]
        if package["name"] == "morphz" and package["id"] in workspace_ids
    ]
    if len(roots) != 1:
        raise RuntimeError("could not identify the Morphz package in Cargo metadata")

    reachable: set[str] = set()
    pending = roots
    while pending:
        package_id = pending.pop()
        if package_id in reachable:
            continue
        reachable.add(package_id)
        node = nodes_by_id.get(package_id)
        if node is None:
            continue
        for dependency in node["deps"]:
            kinds = dependency.get("dep_kinds") or [{"kind": None}]
            if any(kind.get("kind") != "dev" for kind in kinds):
                pending.append(dependency["pkg"])

    packages = []
    for package_id in sorted(reachable):
        package = packages_by_id[package_id]
        if package_id in workspace_ids or package.get("source") is None:
            continue
        package_directory = Path(package["manifest_path"]).parent
        paths = license_files(package_directory, package.get("license_file"))
        if not paths and str(package.get("source", "")).startswith("git+"):
            paths = git_workspace_license_files(package_directory)
        if not paths:
            paths = fallback_license_files(package.get("license") or "")
        packages.append(
            (
                package["name"],
                package["version"],
                package.get("license") or "license-file",
                paths,
            )
        )
    return packages


def npm_package_name(lock_path: str) -> str:
    relative = lock_path.rsplit("node_modules/", 1)[-1]
    parts = relative.split("/")
    return "/".join(parts[:2]) if parts[0].startswith("@") else parts[0]


def dashboard_packages() -> list[tuple[str, str, str, list[Path]]]:
    dashboard_root = REPOSITORY_ROOT / "dashboard"
    lock = json.loads((dashboard_root / "package-lock.json").read_text(encoding="utf-8"))
    packages = []
    for lock_path, package in lock["packages"].items():
        if not lock_path.startswith("node_modules/") or package.get("dev", False):
            continue
        package_directory = dashboard_root / lock_path
        paths = license_files(package_directory)
        if not paths:
            paths = fallback_license_files(package["license"])
        packages.append(
            (
                package.get("name") or npm_package_name(lock_path),
                package["version"],
                package["license"],
                paths,
            )
        )
    return packages


def write_or_check(output: Path, content: str, check: bool) -> None:
    if check:
        if not output.is_file() or output.read_text(encoding="utf-8") != content:
            raise RuntimeError(f"{output.relative_to(REPOSITORY_ROOT)} is out of date")
        return
    output.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("ecosystem", choices=("rust", "dashboard"))
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    if arguments.ecosystem == "rust":
        output = REPOSITORY_ROOT / "THIRD_PARTY_LICENSES_RUST.md"
        content = render_bundle(
            "Third-Party Rust Licenses",
            "This bundle covers non-development Cargo dependencies reachable from the Morphz package across supported targets.",
            rust_packages(),
        )
    else:
        output = REPOSITORY_ROOT / "dashboard" / "THIRD_PARTY_LICENSES.md"
        content = render_bundle(
            "Third-Party Dashboard Licenses",
            "This bundle covers production npm dependencies used to build the Dashboard embedded in Morphz releases.",
            dashboard_packages(),
        )
    write_or_check(output, content, arguments.check)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError, subprocess.CalledProcessError) as error:
        print(f"license generation failed: {error}", file=sys.stderr)
        raise SystemExit(1)
